# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/2_/1_/1/ours/CPUv0.2/CPUv0.2.srcs/sources_1/ip/CM/CM.xci
# IP: The module: 'CM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/2_/1_/1/ours/CPUv0.2/CPUv0.2.srcs/sources_1/ip/CM/CM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/2_/1_/1/ours/CPUv0.2/CPUv0.2.srcs/sources_1/ip/CM/CM.xci
# IP: The module: 'CM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/2_/1_/1/ours/CPUv0.2/CPUv0.2.srcs/sources_1/ip/CM/CM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
